import type { Metadata } from "next";
import { LegalShell } from "@/components/legal/legal-shell";
export const metadata: Metadata = { title: "Segurança", description: "Práticas de segurança e reporte responsável da Gevyro." };
export default function SegurancaPage() { return <LegalShell title="Segurança" description="Práticas adotadas e responsabilidades compartilhadas para proteger contas e dados, sem promessas absolutas.">
  <h2>Controles observados</h2><ul><li>senhas processadas com BCrypt no backend;</li><li>autenticação por JWT em cookie HttpOnly com Secure configurável e SameSite;</li><li>proteção CSRF para operações mutáveis e CORS com origens definidas;</li><li>validação da assinatura de webhooks da Stripe e idempotência de eventos;</li><li>checkout hospedado pela Stripe, evitando trânsito de dados completos do cartão;</li><li>códigos de recuperação com validade curta, hash e limite de tentativas;</li><li>autorização baseada na identidade autenticada em fluxos auditados.</li></ul>
  <h2>Responsabilidade compartilhada</h2><p>Use senha exclusiva, proteja o e-mail associado, encerre sessões em dispositivos compartilhados e limite o acesso de colaboradores. Nunca envie senha, JWT, código de recuperação ou dados completos de cartão ao suporte.</p>
  <h2>Comunicação de vulnerabilidade</h2><p>Relate suspeitas pelo canal de <a href="/contato">Contato</a>, com passos de reprodução e impacto, sem acessar, alterar ou divulgar dados de terceiros. <strong>PENDÊNCIA: estabelecer canal dedicado, SLA e política formal de divulgação responsável.</strong></p>
  <h2>Incidentes</h2><p>A resposta deve incluir registro, contenção, preservação de evidências, avaliação do impacto, correção e análise humana sobre comunicações a titulares e autoridades. <strong>PENDÊNCIA operacional: aprovar responsáveis, contatos de emergência e procedimento interno testado.</strong></p>
  <h2>Continuidade e backup</h2><p>Banco de dados, arquivos e configurações críticas precisam de backup, restauração testada e controle de acesso. <strong>PENDÊNCIA de infraestrutura: confirmar quais backups existem, frequência, retenção, criptografia e testes de restauração.</strong></p>
</LegalShell>; }
