import { LegalShell } from "@/components/legal/legal-shell";
import { LEGAL } from "@/lib/legal";
import { pageMetadata } from "@/lib/seo";
export const metadata = pageMetadata({ title: "Política de Privacidade", description: "Saiba como a Gevyro trata dados pessoais e assegura direitos previstos na LGPD.", path: "/privacidade" });
export default function PrivacidadePage() { return <LegalShell title="Política de Privacidade" description="Como dados pessoais podem ser tratados na Gevyro e quais direitos são assegurados pela Lei Geral de Proteção de Dados (LGPD).">
  <h2>1. Quem trata os dados</h2><p>A Gevyro, CNPJ {LEGAL.cnpj}, trata dados conforme esta Política. <strong>{LEGAL.pending.legalName}</strong> <strong>{LEGAL.pending.address}</strong></p>
  <h2>2. Papéis na LGPD</h2><p>A Gevyro atua como <strong>controladora</strong> para conta, autenticação, contratação, prevenção de fraude, suporte e obrigações próprias. Quanto aos dados inseridos por empresas usuárias sobre seus clientes, produtos, vendas ou funcionários, atua normalmente como <strong>operadora</strong>, seguindo instruções lícitas do cliente-controlador.</p>
  <h2>3. Categorias de dados</h2><ul><li>nome, e-mail, foto e identificadores de conta;</li><li>senha protegida por hash no backend, tokens, confirmações, tentativas e registros de acesso;</li><li>empresas, produtos, estoque, clientes, vendas, pedidos, caixas, relatórios e preferências;</li><li>IP, data e hora, navegador, dispositivo, eventos de erro e logs necessários;</li><li>plano, status e identificadores de cliente/assinatura da Stripe; dados completos de cartão não devem transitar pela Gevyro;</li><li>conteúdo de suporte e dados necessários às integrações ativadas pelo cliente.</li></ul>
  <h2>4. Finalidades e bases legais</h2><p>Os dados podem ser tratados para executar contrato e procedimentos preliminares, autenticar, fornecer recursos, processar assinatura, prestar suporte, cumprir obrigação legal, exercer direitos, prevenir fraude e proteger a plataforma com base em legítimo interesse avaliado. Consentimento será usado somente quando adequado, sem agrupá-lo com tratamentos obrigatórios.</p>
  <h2>5. Fornecedores e compartilhamento</h2><p>O código confirma integrações possíveis com Stripe, Google, serviços de e-mail, Cloudinary, Redis e banco de dados, além de Shopee e Mercado Livre quando conectados. O compartilhamento deve se limitar à função usada. Hospedagem e monitoramento dependem do ambiente. <strong>PENDÊNCIA: manter inventário dos fornecedores efetivamente ativados, localização e salvaguardas.</strong></p>
  <h2>6. Transferência internacional</h2><p>Fornecedores globais podem tratar dados fora do Brasil. Isso deve ser confirmado individualmente e amparado por mecanismo admitido pela LGPD. Não declaramos localização não comprovada.</p>
  <h2>7. Retenção e eliminação</h2><p>Dados serão mantidos enquanto necessários às finalidades, ao contrato e a obrigações legais, fiscais, regulatórias, antifraude, segurança e exercício de direitos; depois, eliminados ou anonimizados quando aplicável. <strong>PENDÊNCIA: aprovar tabela de retenção por categoria.</strong></p>
  <h2>8. Segurança</h2><p>São adotados controles compatíveis com riscos, como autenticação, cookies protegidos, hashing de senha e autorização. Nenhum sistema é absolutamente seguro. Consulte <a href="/seguranca">Segurança</a>.</p>
  <h2>9. Direitos do titular</h2><p>Podem ser solicitados confirmação, acesso, correção, anonimização, bloqueio ou eliminação quando cabíveis, portabilidade conforme regulamentação, informação sobre compartilhamento, revisão automatizada, oposição e revogação de consentimento. A identidade poderá ser verificada.</p>
  <h2>10. Solicitações</h2><p>Use a área “Privacidade e Dados” da conta ou <a href={`mailto:${LEGAL.supportEmail}`}>{LEGAL.supportEmail}</a>. <strong>{LEGAL.pending.privacyEmail}</strong> A exclusão não é automática porque requer análise segura de dependências e retenções legítimas.</p>
  <h2>11. Cookies</h2><p>Consulte a <a href="/cookies">Política de Cookies</a>. Tecnologias necessárias independem de consentimento; as opcionais devem respeitar a preferência registrada.</p>
  <h2>12. Crianças e adolescentes</h2><p>A plataforma empresarial não é direcionada a crianças. Dados de menores eventualmente inseridos pelo cliente exigem base legal e observância do melhor interesse.</p>
  <h2>13. Alterações</h2><p>Mudanças materiais receberão nova versão e comunicação adequada. O titular também pode peticionar à Autoridade Nacional de Proteção de Dados (ANPD).</p>
</LegalShell>; }
