import type { Metadata } from "next";
import { LegalShell } from "@/components/legal/legal-shell";
import { LEGAL } from "@/lib/legal";
export const metadata: Metadata = { title: "Termos de Uso", description: "Termos de Uso da plataforma Gevyro." };
export default function TermosPage() { return <LegalShell title="Termos de Uso" description="Regras iniciais para utilização da plataforma Gevyro. Este documento deve passar por revisão jurídica antes do lançamento comercial definitivo.">
  <h2>1. Identificação e objeto</h2><p>A Gevyro é uma plataforma SaaS de gestão empresarial, acessada pela internet, com funcionalidades de vendas, produtos, estoque, clientes, caixa, relatórios e assinatura. Fornecedor identificado pelo CNPJ {LEGAL.cnpj}. <strong>{LEGAL.pending.legalName}</strong> <strong>{LEGAL.pending.address}</strong></p>
  <h2>2. Conta e credenciais</h2><p>O usuário deve fornecer informações corretas, manter suas credenciais confidenciais e comunicar suspeitas de acesso indevido. A conta é pessoal; ações realizadas por usuários autorizados da empresa são responsabilidade do titular, sem prejuízo das obrigações de segurança da Gevyro. O acesso pode exigir confirmação de e-mail ou autenticação externa.</p>
  <h2>3. Uso permitido</h2><p>A plataforma deve ser usada de forma lícita. É proibido contornar controles, explorar vulnerabilidades, introduzir código malicioso, acessar dados de terceiros, sobrecarregar deliberadamente o serviço ou utilizá-lo para fraude ou violação de direitos.</p>
  <h2>4. Planos e período experimental</h2><p>O projeto informa período experimental de 30 dias e planos pagos mensais Básico, Pro e Premium, com limites e recursos apresentados antes da contratação. <strong>PENDÊNCIA: definir formalmente elegibilidade e conversão após o teste.</strong></p>
  <h2>5. Pagamento e renovação</h2><p>As assinaturas pagas são processadas no ambiente da Stripe e podem ter cobrança recorrente mensal. Preço, periodicidade e plano são mostrados antes do redirecionamento. O status de acesso depende da confirmação confiável do processador; o frontend não ativa planos por conta própria. Falhas de pagamento podem limitar o acesso, observados a legislação e os avisos aplicáveis.</p>
  <h2>6. Cancelamento e reembolso</h2><p>Consulte <a href="/cancelamento-reembolsos">Cancelamento, Assinaturas e Reembolsos</a>. Direitos previstos no Código de Defesa do Consumidor, inclusive arrependimento quando aplicável, permanecem assegurados. <strong>PENDÊNCIA: definir a política comercial de reembolso e confirmar o acesso após cancelamento.</strong></p>
  <h2>7. Dados do cliente</h2><p>O cliente é responsável pela legalidade e permissões relativas aos dados que insere. Para dados tratados em nome da empresa cliente, a Gevyro atua, em regra, como operadora; para conta, cobrança, segurança e relacionamento próprio, pode atuar como controladora.</p>
  <h2>8. Disponibilidade e manutenção</h2><p>Poderão ocorrer manutenções, atualizações, indisponibilidades de fornecedores e eventos fora do controle razoável. A Gevyro adotará esforços compatíveis, sem promessa de disponibilidade absoluta e sem afastar direitos legais.</p>
  <h2>9. Integrações</h2><p>Funcionalidades podem depender de Stripe, Google OAuth, serviços de e-mail, armazenamento de imagens e marketplaces efetivamente habilitados. Cada serviço pode ter termos próprios, permanecendo as responsabilidades previstas em lei.</p>
  <h2>10. Propriedade intelectual</h2><p>A marca, interface e software próprios são protegidos. A assinatura concede direito limitado e não exclusivo de uso durante sua vigência; não transfere o software nem a propriedade dos dados do cliente.</p>
  <h2>11. Responsabilidades</h2><p>A Gevyro responde na extensão prevista em lei. Informações gerenciais não substituem orientação contábil, fiscal ou jurídica. Nenhuma cláusula exclui responsabilidade que não possa ser limitada pela legislação brasileira.</p>
  <h2>12. Suspensão e encerramento</h2><p>O acesso pode ser suspenso por risco de segurança, violação relevante, obrigação legal ou inadimplência, com comunicação quando cabível. A exclusão exige análise de retenções legais, fiscais, antifraude e de segurança; não implica eliminação imediata de todos os registros.</p>
  <h2>13. Alterações e histórico</h2><p>Alterações relevantes terão nova versão e data. Quando necessário, haverá nova ciência ou aceite. <strong>PENDÊNCIA técnica: registrar de modo auditável a versão apresentada ou aceita.</strong></p>
  <h2>14. Contato</h2><p>Dúvidas: <a href={`mailto:${LEGAL.supportEmail}`}>{LEGAL.supportEmail}</a>. A legislação brasileira e o foro legalmente competente são preservados, inclusive o domicílio do consumidor quando aplicável.</p>
</LegalShell>; }
